[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .

markers =
    smoke: quick smoke tests
    regression: full regression tests
    ui: ui tests
    api: api tests
    external: tests using external services
