[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .

markers =
    smoke: быстрые критические тесты
    regression: полный набор
    external: тесты требующие внешних сервисов
    api: API тесты
    ui: UI тесты
